default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --frozen ruff check
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: uv run --frozen ruff format --check
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ty
        name: ty
        entry: uv run --frozen ty check src tests
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        always_run: true
        require_serial: true

      - id: typos
        name: typos
        entry: uv run --frozen typos --force-exclude
        language: system
        types: [text]
        require_serial: true
