name: Publish a release

# GitHub events that triggers the workflow:
on:
  release:
    types:
      - published

jobs:
  call_test_workflow:
    name: Run Tests
    uses: ./.github/workflows/test.yaml

  upload_release_files:
    name: Create release files
    needs:
      - call_test_workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build
        run: |
          hatch build

      - name: Upload the package as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/jaxellip-*.tar.gz
            dist/jaxellip-*.whl

  publish_to_pypi:
    name: Publish to PyPI
    needs:
      - upload_release_files
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Check if the release tag matches the version
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: jaxellip/__init__.py

      - name: Build
        run: |
          hatch build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Upload the wheel and source distribution as artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
