name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Check
        run: just check

      - name: Run prek hooks
        run: just prek

  test:
    name: Test with Py${{ matrix.python-version }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ["3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Test
        run: just test-and-report

      - name: Rename the coverage file
        run: >
          uv run --frozen python -c
          "from pathlib import Path;
          Path('.coverage').rename('.coverage.${{ matrix.python-version }}.${{ matrix.os }}')"

      - name: Upload coverage as an artifact
        uses: actions/upload-artifact@v7
        with:
          include-hidden-files: true
          name: coverage-${{ matrix.python-version }}-${{ matrix.os }}
          path: .coverage.${{ matrix.python-version }}.${{ matrix.os }}

  report-coverage:
    name: Generate the coverage report
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download coverage files
        uses: actions/download-artifact@v8
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Combine coverage files
        run: just coverage-report

      - name: Upload the coverage report to smokeshow
        run: uv tool run smokeshow==0.4.0 upload ./htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 90
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
